<div class="container">
  <h1>Več o furryjih</h1>
  <p>Morda ste o furryjih že kaj slišali ali prebrali, morda ste naleteli na to temo ob brskanju po spletu, vsekakor domnevamo, da če že berete to besedilo, vas tema zanima. Torej, kaj točno je furry?</p>
  <p>Odgovor na to vprašanje vsekakor ni enostaven, niti ni enoličen. Lahko bi rekli, da toliko kot je na svetu furryjev, toliko je odgovorov. Razlog za to leži v dejstvu, da furry fandom oz. furry skupnost ni nastala organizirano, kot skupina oboževalcev točno določene entitete (kotna primer oboževalci Harry Potterja, Star Treka in podobno), ampak kot skupina ljudi, ki jih fascinirajo živali s človeškimi lastnostmi. Beseda »furry« je namreč angleški samostalnik, ki pomeni kosmato, z dlako. V angleščini se za označevanje živali s človeškimi lastnostmi pogosto uporablja izraz »anthropomorphic«, torej antropomorfno, ki izvira iz grške besedne zveze »Anthropos Morphe« (človeška podoba). Tako furryje fascinirajo živali, ki jim, denimo, pripišemo človeški um, način sporazumevanja, nekateri pa jim pripisujejo tudi obliko, torej stojo na dveh nogah. Vsekakor pa to ni vse, saj je svet domišljije omejen le toliko, kot si ga omejimo sami. Prav tako furryji, kljub osnovnemu pomenu besede, niso omejeni na bitja z dlako, v furry fandomu boste našli tudi privržence z luskami pokritih živali, kot na primer kače. furryji se tudi ne omejujejo na obstajajoče vrste, našli boste od namišljenih in križanih vrst, ki so jih ustvarili furryji sami, do vrst o katerih ste morda slišali v starodavnih legendah, bajkah, zgodbah ali zgodovinskih virih, kot so zmaji, troglavi pes Cerberus ali pa morda bog Anubis (iz Egipčanske mitologije).</p>

  <div class="text-center mb-3">
    <img src="<?php echo URL; ?>public/img/anubis.jpg" class="rounded" height="200px">
  </div>
  <p class="text-center"><b>Slika Anubisa, kot ga je upodobila furry umetnica <a href="http://www.furaffinity.net/user/darknatasha/" target="_blank">DarkNatasha</a></b></p>

  <p>Prav razmislek in kratek pregled zgodovinskih dejstev nam hitro razkrije, da so bili ljudje od samega začetka povezani z živalmi. Nekatere sočloveku predstavljale hrano, druge delovno silo, tretje zaščito in tako je človek od nekdaj z določenimi živalmi tvoril povezave in jih vključeval v svojo življenjsko skupnost, kar vidimo še danes, ko se sprehajamo v parku in opazujemo vesele lastnike, ki sprehajajo domače živali. Nekatere živali v ljudeh zbujajo strah, druge fascinacijo, ki je prav v primeru stare Egipčanske kulture prerasla v čaščenje določenih živalskih vrst. Seveda Egipčani niso bili edini, še danes lahko najdemo določena verstva, ki so tesno povezana z živalmi. Znano je tudi, da mnoge živali v človeku vzbujajo pozitivna čustva, lastniki domačih ljubljenčkov naj bi bili bolj sproščeni, tudi vznemirjenega otroka je moč nekoliko umiriti z njegovo najljubšo plišasto živaljo, ob kateri se bo počutil varnejšega, bolj zadovoljnega in sproščenega.</p>

  <div class="text-center mb-3">
    <img src="<?php echo URL; ?>public/img/plushie.jpg" class="rounded" height="200px">
  </div>

  <p>Ker živimo v potrošniško naravnanem svetu, kjer se od posameznika pričakuje vse večja učinkovitost, kjer posameznik ni več pomemben kot individuum ampak zgolj kot številka, ki predstavlja njegovo učinkovitost, čutijo ljudje vse večjo potrebo po občasni sprostitvi, po prijetnem druženju s prijatelji, ali pa preprosto po duhovnem begu pred duhamorno napetostjo, ki jo povzroča pritisk vsakdanjega vrveža. To je vodilo k vzponu in razvoju številnih domišljijskih žanrov in posledično aktivnosti, med katere spada tudi furry skupnost. Kot se številni oboževalci RPG iger in drugih domišljijskih aktivnosti z veseljem dobijo in predajo svetu igre, v katerem vladajo popolnoma druga pravila, tako nekaterim furryjem fandom predstavlja možnost vstopa v svet, ki si ga ustvarijo sami, v svet, v katerem se pojavijo kot njihove fursone (kot furryji imenujejo lika, ki jih predstavlja). To pa ne velja za vse furryje. Furry fandom je, kot že omenjeno, zelo raznolik, zato boste našli v njem lahko zgolj ljudi, ki jih zanimajo risanke in animirani filmi, v katerih se pojavijo vsem znani kosmati junaki, spet tretje morda fascinira zgolj ustvarjanje umetniških del, ki so povezane z antropomorfnimi živalmi.</p>

  <div class="text-center mb-3">
    <img src="<?php echo URL; ?>public/img/artemis_pinup.jpg" class="rounded" height="200px">
  </div>
  <p class="text-center"><b>Fursona lisjak, karakter furryja <a href="http://www.furaffinity.net/user/darkdragon452" target="_blank">darkdragon452</a>, narisala <a href="http://www.furaffinity.net/user/princessrei" target="_blank">princessrei</a></b></p>

  <p>Ravno ta raznolikost, ki fandomu daje neizmerno širino, pa je lahko občasno tudi problematična, saj se pogosto najdejo posamezniki z zelo različnimi pogledi na določene stvari, kar lahko vodi do nekaterih nesporazumov. Fandom namreč sestavljajo ljudje skoraj vseh starosti, narodnosti, verskih pripadnosti in področji izobrazbe. Fandom je znan po močno poudarjeni odprtosti in sprejemanju ljudi takšnih kot so in takšnih kot si želijo biti, kar je fandomu prineslo po eni strani številne člane in odobravanje mnogih, po drugi strani pa tudi neodobravanje in kritiziranje s strani tistih bolj ozkogledih in konservativnih.</p>

  <p>Sami začetki fandoma segajo v 70 in 80 leta prejšnjega stoletja. Vse naj bi se začelo na zborovanju oboževalcev znanstvene fantastike, ko je stekla beseda o živalih s človeškimi lastnostmi. To je pritegnilo pozornost nekaterih prisotnih in osnovala se je skupina interesentov, ki je nadaljevala tradicijo na nadaljnjih znanstvenofantastičnih zborovanjih in zborovanjih povezanih s stripi. S pojavom in svetovno širitvijo interneta se je tudi fandom začel vse bolj širiti, saj je internet predstavljaj medij, ki je odstranil geografske ovire uporabnikom in tako so nastale številne furry skupine, ki so se razvijale in rastle skupaj z razvojem interneta. Poleg tega, je bilo leta 1987organizirano prvo furry zborovanje v ZDA, kar je še dodatno pospešilo razvoj fandoma, v okviru katerega se danes po celem svetu organizira preko50 različnih mednarodnih zborovanj in nepredstavljivo število lokalnih srečanj.</p>

  <div class="text-center mb-3">
    <img src="<?php echo URL; ?>public/img/anthrocon.jpg" class="rounded" height="200px">
  </div>
  <p class="text-center"><b>Tržnica na Anthroconu</b></p>

  <p>Kljub deljenim mnenjem, se večina strinja, da je osrednji medij furry fandoma furry umetnost. Gre predvsem za slike, narejene v najrazličnejših tehnikah, ki prikazujejo furry karakterje. Velik del furry umetnosti se izmenjuje preko interneta in številnih spletnih strani, namenjenih prikazovanju teh stvaritev, del izmenjave in prikazovanja pa poteka tudi na zborovanjih, kjer pogosto najdete umetniško razstavo, ki ji sledi tudi avkcija določenih umetnin. Poleg razstave furry umetnosti pa se na zborovanjih odvijajo številne druge aktivnosti, pogosti so kratki seminarji, katerih tema je lahko bolj ali manj povezana s fandomom, srečanje skupinic raznovrstnih interesentov (znotraj fandoma lahko srečate številne navdušence nad najrazličnejšimi področji, od elektronike, avtomobilizma, filozofije in številnimi drugimi), različnih zabavnih predstav, ki se lahko gibljejo striktno znotraj interesa furry fandoma (lutkovna predstava z živalskimi lutkami) ali pa jih zgolj izvajajo predstavniki fandoma ( stand-up komedija, glasbeni nastopi in podobno), pogosti so tudi plesi s glasbo, ki trajajo pozno v noč. Vsekakor pa je osrednji namen zborovanj predvsem druženje in zabava.</p>

  <div class="text-center mb-3">
    <img src="<?php echo URL; ?>public/img/motofurs.jpg" class="rounded" height="200px">
    <img src="<?php echo URL; ?>public/img/dance.jpg" class="rounded" height="200px">
  </div>
  <p class="text-center"><b>Levo: Motofurs na zborovanju <a href="http://www.confuzzled.org.uk/" target="_blank">Confuzzled</a>, kjer furryji razkažejo svoja vozila; desno: ples na zborovanju <a href="http://www.eurofurence.org/" target="_blank">Eurofurence</a></b></p>

  <p>Ko govorimo o furry zborovanjih in aktivnostih, nikakor ne smemo pozabiti na fursuiting. Beseda fursuiting izhaja iz besede fursuit, kar prevedemo kot »kosmata obleka« in na prvi pogled, to tudi je. Nekateri furryji, bolj natančno okoli 20-25%, imajo enega ali več živalskih kostumov, v katere se oblečejo in v njih udeležujejo raznovrstnih aktivnostih. Če ste ob tem pomislili na živalske kostume, ki jih je možno kupiti v času pusta v trgovini, ste se zelo zmotili o njihovem izgledu. Fursuit je unikaten kostum, ki si ga lastnik izdela sam, ali pa ga naroči pri katerem od izdelovalcev in je narejen natančno po karakterju, ki naj bi ga predstavljal. Fursuiti so namenjeni večletni uporabi, njihova izdelava traja okoli mesec dni, če ga izdeluje profesionalni izdelovalec, lahko pa tudi dlje, odvisno od zahtevnosti izgleda lika. Cena fursuita se večinoma giblje med 1000 in 3000€, nekateri pa dosegajo celo cene preko 7000€. Cena je odvisna od podrobnosti in značilnosti kostuma, kot tudi številnih dodatkov, recimo elektronskega premikanja ušes. Verjetno se sedaj sprašujete, zakaj bi nekdo vložil toliko denarja v nakup kostuma, za oblačenje katerega bo potreboval okoli 15 minut, v katerem bo okoli 40-50C ko ga bo nosil in v katerem bo imel omejeno vidljivost. Odgovor fursuiterjev zelo preprost, zato, da bi se zabavali. Poleg fursuitov, so pogosti tudi partial fursuiti ali delni kostumi, ki jih sestavlja zgolj glava (maska), šape in rep. Nekateri se za partial fursuit odločijo zaradi cene, ki je lahko opazno nižja, ali pa zaradi dejstva, da pokriva manjši del telesa, kar pomeni tudi boljše hlajenje. Poleg udeležb na številnih posebej pripravljenih aktivnostih za fursuiterje, boste furryje v kostimih videli tudi na plesih ali pa kar tako na zborovanjih, kjer bodo številnim udeležencem naslikali nasmeh na obraze. Omeniti gre tudi, da se aktivnosti fursuiterjev ne končajo zgolj na zborovanjih. Nekateri fursuiterji delujejo kot profesionalne maskote določenih športnih moštev (vendar ne z lastnim fursuitom), spet drugi se vključujejo v dobrodelne akcije kjer jih pomagajo promovirati. Nekateri se vključujejo v programe pomoči otrokom s posebnimi potrebami ali pa obiščejo otroške bolnišnične oddelke, da bi bolnikom polepšali dan. Vendar so to le nekatere od številnih aktivnosti, s katerimi furryji poskušajo svoje veselje in srečo deliti tudi z drugimi, tudi če to pomeni le prehod v parku, ki bo prav tako nasmejal večino mimoidočih.</p>

  <div class="text-center mb-3">
    <img src="<?php echo URL; ?>public/img/artie.jpg" class="rounded" height="200px">
    <img src="<?php echo URL; ?>public/img/fursuit_base.jpg" class="rounded" height="200px">
  </div>
  <p class="text-center"><b>Levo: Fursuiter, arktični lisjak, kostum pripada <a href="http://www.furaffinity.net/user/artie/" target="_blank">artie-ju</a>, izdelovalec <a href="http://www.onefurall.com/" target="_blank">Studio OneFurAll</a>; desno: penasta osnova za glavo fursuita, izdelovalka <a href="http://www.furaffinity.net/user/shengoh/" target="_blank">Shengoh</a></b></p>

  <p>Na prvi pogled se vam furryji morda zdijo nekoliko čudni in verjemite, niste edini. Ravno zaradi te neobičajnosti, pa tudi drugih nesporazumov, je bil furry fandom dolga leta na udaru senzacionalističnih novinarjev, ki so iskali naslednjo šokantno zgodbo in zdolgočasenih uporabnikov interneta, ki se zabavajo s kritiziranjem vsega kar vidijo. Kljub nekaterim izjemam, je fandom skozi leta dokazoval ljudem, da so tudi furryji le običajni ljudje, ki imajo nekoliko drugače interese, kot bi jih od njih pričakovala družba. Danes so tudi pogledi na fandom večinoma drugačni, kot so bili pred nekaj leti.</p>

  <p>Čeprav morda nobenega fursuterja še niste srečali v Sloveniji, lahko najdete furryje tudi v naši lepi deželici na sončni strani Alp. Znanih je okoli 40-60, vendar se jih aktivno udeležuje slovenskih srečanj le okoli 20-25.</p>

  <div class="text-center mb-3">
    <img src="<?php echo URL; ?>public/img/header.jpg" class="rounded" height="200px">
  </div>
  <p class="text-center"><b>Fursuiterji na srečanju slovenskih furrijev</b></p>

  <p>Če želite o fandomu izvedeti več, si lahko preberete več na <a href="http://www.anthrocon.org/" target="_blank">spletnih straneh Anthrocona</a>, največjega svetovnega zborovanja furryjev ali pa na <a href="http://www.crofurry.org/" target="_blank">spletni strani naših sosedov Hrvatov</a>. Če se vam kljub temu poraja kako vprašanje, smo vam na voljo na <a href="mailto:info@slofurs.org" target="_blank">info@slofurs.org</a>, na <a href="https://twitter.com/slofurs" target="_blank">SloFurs Twitterju</a> ter <a href="https://discord.gg/0eaoyLCJ7eiTMBaj" target="_blank">SloFurs Discord strežniku</a>, enako velja, če se nam želite pridružiti; lahko pa se udeležite tudi katerega od prihajajočih srečanj.</p>

</div>
